pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS_ID = 'docker'
        DOCKER_REGISTRY = "sumaiyap"
        REPO_URL = "https://github.com/sumaiyap/events.git"
        AWS_REGION  = "us-east-1"
        ACCOUNT_ID = "905418023088"

    }

    stages {
        stage('Login to Docker Hub') {
          steps {
                script {
                    withCredentials([usernamePassword(credentialsId: DOCKERHUB_CREDENTIALS_ID, usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                        sh 'docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD'
                    }
                }
            } 
        }

        stage('Build and Push frontend') {
            steps {
                script {
                    dir('application/frontend/events') {
                        sh '''
                            id
                            ls -al
                            echo "current working dir: `pwd`"
                            docker build -t frontend:latest .
                            trivy image frontend:latest > frontend_report.txt
                            docker tag frontend:latest ${DOCKER_REGISTRY}/frontend:latest
                            docker push ${DOCKER_REGISTRY}/frontend:latest
                        '''
                    }
                }
            }
        }

        stage('Build and Push backend') {
            steps {
                script {
                    dir('application/backend') {
                        sh '''
                            id
                            ls -al
                            echo "current working dir: `pwd`"
                            docker build -t backend:latest .
                            trivy image backend:latest > backend_report.txt
                            docker tag backend:latest ${DOCKER_REGISTRY}/backend:latest
                            docker push ${DOCKER_REGISTRY}/backend:latest
                        '''
                    }
                }
            }
        }


    }
}
